apiVersion: v1
kind: Namespace
metadata:
  name: unixway
---
apiVersion: v1
kind: Pod
metadata:
  name: database-memory
  namespace: unixway
  labels:
    role: database
spec:
  containers:
    - name: app
      image: postgres:11
      ports:
        - name: database-port
          containerPort: 5432
          protocol: TCP
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data-volume
  volumes:
  - name: data-volume
    emptyDir:
      medium: "Memory"
      sizeLimit: "1Gi"
