apiVersion: v1
kind: Namespace
metadata:
  name: unixway
---
apiVersion: v1
kind: Pod
metadata:
  name: database-raw
  namespace: unixway
  labels:
    role: database
spec:
  containers:
    - name: app
      image: postgres:11
      ports:
        - name: database-port
          containerPort: 5432
          protocol: TCP
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
