apiVersion: v1
kind: Namespace
metadata:
  name: unixway
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: database-nfs-statefulset
  namespace: unixway
spec:
  selector:
    matchLabels:
      role: database
  serviceName: "database"
  replicas: 2
  template:
    metadata:
      name: database-nfs-statefulset
      labels:
        role: database
    spec:
      containers:
        - name: app
          image: postgres:11
          ports:
            - name: database-port
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data-volume
  volumeClaimTemplates:
  - metadata:
      name: data-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: managed-nfs-storage
      resources:
        requests:
          storage: 1Gi
