apiVersion: v1
kind: Namespace
metadata:
  name: unixway
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim1
  namespace: unixway
spec:
  storageClassName: 'managed-nfs-storage'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: database-nfs-deployment
  namespace: unixway
spec:
  selector:
    matchLabels:
      role: database
  replicas: 5
  strategy:
    type: Recreate
  template:
    metadata:
      name: database-nfs-deployment
      labels:
        role: database
    spec:
      containers:
        - name: app
          image: postgres:11
          ports:
            - name: database-port
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data-volume
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: nfs-claim1
