apiVersion: v1
kind: Namespace
metadata:
  name: unixway
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-volume1
spec:
  storageClassName: 'nfs-ssd'
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/volume1
    server: 192.168.122.210
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim1
  namespace: unixway
spec:
  storageClassName: 'nfs-ssd'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: database-nfs-claim
  namespace: unixway
  labels:
    role: database
spec:
  containers:
    - name: app
      image: postgres:11
      ports:
        - name: database-port
          containerPort: 5432
          protocol: TCP
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"
      volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: data-volume
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: nfs-claim1
